### ISSUE TITLE
ProtoSSL. Aries clients not working with the current SSLv3 engine.

### ISSUE THREAD

**Issue by GitHubProUser67** [valters-tomsons/arcadia#19]
Hello valters-tomsons,

Before explaining the issue, I want to thank you a lot for your FESL handling in C#! Very very handy for Theatre based clients, however, there is a problem with older Aries based clients using SSLv3 like theatre (maybe blaze too).

The bouncycastle certificate pair is always rejected by the game, despite the correct CN added to the certificate itself.

An example here with Nascar09 PS3.

![image](https://github.com/valters-tomsons/arcadia/assets/127040195/ca274d4f-5d39-4819-8255-c4116a575eda)

This also happens in some Theatre games, such as Mirrors Edge, the code here is the exact same as your's, just used in a different way ( https://github.com/GitHubProUser67/MultiServer3/blob/main/SpecializedServers/MultiSocks/DirtySocks/DirtySockClient.cs ).

(PS: don't worry, I will add the credits for your fesl engine).

Hopefully we can find why it does that. I am willing to help if needed.

**Comment by valters-tomsons** [comment]
Most likely the game does not use a vulnerable ProtoSSL version, same can be seen for BF: Bad Company 1 & Army of Two.

I have not done exhaustive research on this, but it looks like games released before 2009 are generally not vulnerable.

**Comment by GitHubProUser67** [comment]
Ok. However, there seem to be something else at play, eaEmu has a cert generator that works with Burnout Paradise PC, which is one of these games that won't work with the vulnerable approach. It is using OpenSSL to do so.

I will try out stuff and let you know.

**Comment by GitHubProUser67** [comment]
So, I found out a couple of things, firstly there exist some vulnerable Aries clients, but the ProtoSSL is so old it only takes MD5 signature.

I fixed your code to also handle the MD5 case, there was also an issue with the issuer where the extra " " were messing up the certificate verification process.

https://github.com/GitHubProUser67/MultiServer3/blob/Nightly/SpecializedServers/MultiSocks/Tls/ProtoSSLUtils.cs

However, do you have a trick to patch PS3 eboots from non-vulnerable protoSSL versions?

Thanks in advance.
